// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewBookLendApi.Models;

namespace NewBookLendApi.Migrations
{
    [DbContext(typeof(BooklprjtContext))]
    [Migration("20211118104904_Booklprjt")]
    partial class Booklprjt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewBookLendApi.Models.Booktbl", b =>
                {
                    b.Property<int>("BId")
                        .HasColumnType("int")
                        .HasColumnName("bId");

                    b.Property<string>("Bookname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cname");

                    b.HasKey("BId");

                    b.HasIndex("Cname");

                    b.ToTable("Booktbl");
                });

            modelBuilder.Entity("NewBookLendApi.Models.Categoytbl", b =>
                {
                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Category")
                        .HasName("PK_Categoytbl_1");

                    b.ToTable("Categoytbl");
                });

            modelBuilder.Entity("NewBookLendApi.Models.UserTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bookname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("bookname");

                    b.Property<string>("Bookreqno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("bookreqno");

                    b.Property<string>("Catergory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("catergory");

                    b.Property<int?>("Cost")
                        .HasColumnType("int")
                        .HasColumnName("cost");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("Lendeddate")
                        .HasColumnType("date")
                        .HasColumnName("lendeddate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("Returndate")
                        .HasColumnType("date")
                        .HasColumnName("returndate");

                    b.HasKey("Id");

                    b.ToTable("UserTable");
                });

            modelBuilder.Entity("NewBookLendApi.Models.Booktbl", b =>
                {
                    b.HasOne("NewBookLendApi.Models.Categoytbl", "CnameNavigation")
                        .WithMany("Booktbls")
                        .HasForeignKey("Cname")
                        .HasConstraintName("FK__Booktbl__cname__3D5E1FD2");

                    b.Navigation("CnameNavigation");
                });

            modelBuilder.Entity("NewBookLendApi.Models.Categoytbl", b =>
                {
                    b.Navigation("Booktbls");
                });
#pragma warning restore 612, 618
        }
    }
}
